language: java
before_install:
  - "export NOW=$(date +%s)"
  - "echo $NOW"
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"
deploy:
  provider: script
  script: 
  - "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -Drevision=1.14.4-R0.1-$NOW deploy"
  skip_cleanup: true
